version: "3.8"

networks:
  1panel-network:
    external: true

services:
  iycms:
    image: qyg2297248353/iycms:v3.3.44
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:80
      - ${PANEL_APP_PORT_ADMIN}:21007
